# RootedCON 2024 (08/03)
- Antonio Sanz [Piñatas, palos y joputas: cómo investigar incidentes de ciberseguridad](https://raw.githubusercontent.com/ProtAAPP/wikiprot/master/docs/01_introduccion/ponencias/rootedcon24/Pi%C3%B1atas%2C%20palos%20y%20joputas%20-%20C%C3%B3mo%20investigar%20incidentes%20de%20seguridad_DEF3.pdf)
- Emilio Rico [Somos agentes de la T.I.A.](https://raw.githubusercontent.com/3MilioRR/conferences/main/Somos%20los%20agentes%20de%20la%20TIA%20%5BRootedCON%202024%5D.pdf)
- Marta Beltrán [Por la cara: retos y oportunidades asociados al reconocimiento]
- Manuel Guerra [FlipperZero, del ataque a la mesa de autopsias](https://raw.githubusercontent.com/ProtAAPP/wikiprot/master/docs/01_introduccion/ponencias/rootedcon24/Flipper%20Zero%20Forensic%20MANUEL%20GUERRA.pdf)
- Pablo González y Fran Ramirez [Garfunkel: Tu co-piloto para auditar inteligencia artificial]
- Miguel de la Cal y Félix Paniagua [External Attack Surface Management: DIY for free!](https://raw.githubusercontent.com/ProtAAPP/wikiprot/master/docs/01_introduccion/ponencias/rootedcon24/ASM_DIY-Miguel-Felix.pdf)
- Diego Balboa [HIGHWAY TO RHEL (AC/BC). Auditoría, fortificación y remediación perpetua automatizada de sistemas mediante Infrastructure as Code (IaC). Security as Code (SaC)](https://raw.githubusercontent.com/ProtAAPP/wikiprot/master/docs/01_introduccion/ponencias/rootedcon24/2024-ProtAAPP-RootedCON-dbr.pdf)
- Jesús Cuadrado y Daniel "Cr0hn" González [Apificando y securizando, que es gerundio. Seguridad en APIs del Ayuntamiento de Madrid](https://raw.githubusercontent.com/ProtAAPP/wikiprot/master/docs/01_introduccion/ponencias/rootedcon24/Apificandoqueesgerundio.pdf)
- Nuria Prieto [El secreto está en las Cookies](https://raw.githubusercontent.com/ProtAAPP/wikiprot/master/docs/01_introduccion/ponencias/rootedcon24/NuriaPrietoElsecretoestaenlasCookies.pdf)
- Ángel del Peso, María Oliva y Olga Mata [Un estreno de ciencia]
